### ISSUE TITLE
Private channels and Laravel cookie encryption

### ISSUE THREAD

**Issue by sriccio** [mvanduijker/laravel-mercure-broadcaster#12]
Hello,

Thanks a lot for this implementation of mercure broadcaster for laravel.

I just would like to expose an "issue" I've been fighting with while trying to use this in a project.

It looks like by default, or at least when using a pre-built authentication stack, Laravel encrypt all cookies. So for private channels using the cookie middleware, the resulting cookie gets encrypted and cannot be parsed by the Mercure hub.

This resulted in this kind of log entries on the Hub:

```
mercure_1  | {"level":"info","ts":1645187479.2805336,"logger":"http.handlers.mercure","msg":"Subscriber unauthorized","subscriber":{"id":"urn:uuid:05fcf9f7-8564-45f3-952b-a8abaafadd54","last_event_id":"","remote_addr":"172.21.0.1:48160"},"error":"unable to parse JWT: token contains an invalid number of segments"}
```

After digging a bit I found out that you can exclude cookie names from Laravel encryption by adding an `App/Middleware/EncryptCookies.php` middleware and declare the cookies name to be left unencrypted in it.

```
<?php

namespace App\Http\Middleware;

use Illuminate\Cookie\Middleware\EncryptCookies as Middleware;

class EncryptCookies extends Middleware
{
    /**
     * The names of the cookies that should not be encrypted.
     *
     * @var array<int, string>
     */
    protected $except = [
        'mercureAuthorization'
    ];
}
```

This resolved the issue for me. The client can now subscribe to the private channel.

```
mercure_1  | {"level":"info","ts":1645189281.517158,"logger":"http.handlers.mercure","msg":"New subscriber","subscriber":{"id":"urn:uuid:5cb3e680-d9a2-4fec-ba0b-a173736024ce","last_event_id":"","remote_addr":"172.21.0.1:48188","topic_selectors":["https://vpanel/user/05a39255-a0ab-4ecd-98dc-708ab9b61ae8/direct-messages"],"topics":["https://vpanel/user/05a39255-a0ab-4ecd-98dc-708ab9b61ae8/direct-messages"]}}
```
 Maybe this should appear somewhere in the README ?

Kind regards

**Comment by mvanduijker** [comment]
Thanks for making this issue. Making something for https://github.com/mvanduijker/laravel-mercure-broadcaster/issues/9 would have helped massively. For now I will add something in the README.

**Comment by mvanduijker** [comment]
I've updated the readme. https://github.com/mvanduijker/laravel-mercure-broadcaster/commit/a0c0d0b6d6af71854a6058547ef7cb83f91b8e3d
