### ISSUE TITLE
Question about channels

### ISSUE THREAD

**Issue by your-baby-dev** [mvanduijker/laravel-mercure-broadcaster#13]
Hi, I try to implement your package on my app', I want to add channel (in channels.php, but i don't know if it's necessary)

With something like this : 
`
Broadcast::channel('{user}.example', fn() => true);
`

When run composer install, Laravel throw me an error : 
`  #message: "Call to undefined method Duijker\LaravelMercureBroadcaster\Broadcasting\Broadcasters\MercureBroadcaster::channel()"
  #code: 0
  #file: "./vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php"
`

The "channel()" method refer to "Broadcast::channel()" methods in channels.php.
Are there alternative existing ? Or maybe i can't need to declare a channel, the package do not map model's attribute  to change it state in real time ?

Do you have an example of your package implementation in Laravel from scratch ? Thanks

**Comment by michaelaguiar** [comment]
Also curious about this. Do we not use channels.php anymore?
