### ISSUE TITLE
How to use with self-signed SSL in localhost

### ISSUE THREAD

**Issue by Brouilles** [mvanduijker/laravel-mercure-broadcaster#14]
I have setup mercure with the docker-compose. It used a self-signed certificate and I don't find how to allow Laravel to send the request with this package.

I have the following error
```
[previous exception] [object] (Symfony\\Component\\HttpClient\\Exception\\TransportException(code: 0): SSL certificate problem: unable to get local issuer certificate for \"https://localhost/.well-known/mercure\". at C:\\laragon\\www\\premo\\vendor\\symfony\\http-client\\Chunk\\ErrorChunk.php:56)
```

Here the docker-compose:
```
# docker-compose.yml
version: "3.7"

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      # SERVER_NAME: ':1337'
      MERCURE_PUBLISHER_JWT_KEY: 'ChangeMe'
      MERCURE_SUBSCRIBER_JWT_KEY: 'ChangeMe'
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins *
    # Comment / Uncomment - the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  ```
  
Why I need SSL on localhost? Because otherwise the browser use Http/1.1 and I have already reached the connection limit. But with Http/2 the limit is a lot more (about 100).

**Comment by mvanduijker** [comment]
Was just typing an answer. How did you solve it?

**Comment by Brouilles** [comment]
I don't really solve it. I have always
```
SSL certificate problem: self signed certificate for
```

**Comment by mvanduijker** [comment]
This integration relies heavily on the Symfony Mercure library (https://github.com/symfony/mercure) Which uses the Symfony Http client. Their suggestion (https://symfony.com/doc/current/http_client.html#https-certificates) is to add your own CA and add it to your system's store. Or disable the checks. You could do this by overriding the BroadcastManager::class service (in your own service provider) and inject a HttpClient with the disabled flags in the Hub constructor. https://github.com/symfony/mercure/blob/main/src/Hub.php#L40

**Comment by Brouilles** [comment]
For the docker part, I just updated the volumes to override default certificate with the one I used with laragon 
```
      - "C:/laragon/etc/ssl/laragon.crt:/data/caddy/certificates/local/localhost/localhost.crt"
      - "C:/laragon/etc/ssl/laragon.key:/data/caddy/certificates/local/localhost/localhost.key"
```
Maybe it can help someone in the futur. But the problem is the same, with a different error `SSL certificate problem: self signed certificate for`. Even if the certificate is in the OS store.

**Comment by Brouilles** [comment]
Just  a suggestion, can be cool to have an option like with Laravel email:
```
   'ssl' => [
       'allow_self_signed' => true,
       'verify_peer' => false,
       'verify_peer_name' => false,
   ],
```

**Comment by mvanduijker** [comment]
nice suggestion, will take a look into it

**Comment by Brouilles** [comment]
> This integration relies heavily on the Symfony Mercure library (https://github.com/symfony/mercure) Which uses the Symfony Http client. Their suggestion (https://symfony.com/doc/current/http_client.html#https-certificates) is to add your own CA and add it to your system's store. Or disable the checks. You could do this by overriding the BroadcastManager::class service (in your own service provider) (https://github.com/mvanduijker/laravel-mercure-broadcaster/blob/master/src/LaravelMercureBroadcasterServiceProvider.php#L18) and inject a HttpClient with the disabled flags in the Hub constructor. https://github.com/symfony/mercure/blob/main/src/Hub.php#L40

And thanks a lot, it's work.
